Sprint1/step1
DangerBadger/react-burger pull request #1
Opened 2023-08-02 13:52 UTC by DangerBadger

1. Add Header, BurgerConstructor, BurgerIngredients elements.
2. Adjust code style.

2023-08-02 16:38 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали **очень хорошую** работу на старте вашего проекта, вёрстка корректная и аккуратная, код лаконичный и не содержит лишнего, использованы функциональные компоненты, **так держать** 👍

Тем не менее, для успешной сдачи работы на данном этапе вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Для компонентов с пропсами следует описать `propTypes`. Если в качестве пропсов передается объект или массив объектов, то в `propTypes` описывается структура этого объекта;
- Согласно дизайну ширина заголовка не должна растягиваться на всю ширину экрана, а соответствует ширине контейнера снизу;
- Не следует объединять в рамках одного компонента описания вложенных компонентов. Это усложняет поддержку, тестирование и переиспользуемость. Данную функцию следует вынести в отдельную директорию и файл;
- Ключ следует определять не внутри компонента, а в рамках функции внутри `map`;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:


- Распространенной практикой именования файлов в проекте является стиль `kebab-case`, где не используются заглавные буквы, а разделение слов в названии производится за счет тире. Это позволяет избежать ошибок, когда в регистро-независимых файловых системах проект собирается, а на других нет. 

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления комментариев выше и указанных в коде с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-08-02 16:38 UTC, randomroot commented on src/components/App/App.module.css
> +  /* max-height: 100vh;
🟡 **Можно улучшить:**

Закомментированный код или стилизацию лучше удалить, чтобы поддерживать чистоту кода. При необходимости их можно восстановить средствами Git-a

2023-08-02 16:38 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  function ingredientItem({ _id, name, price, image }) {
🔴 **Нужно исправить:**

Не следует объединять в рамках одного компонента описания вложенных компонентов. Это усложняет поддержку, тестирование и переиспользуемость. Данную функцию следует вынести в отдельную директорию и файл, например `BurgerIngredientItem`

2023-08-02 16:38 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +      <li key={_id} className={burgerIngredients.ingredient}>
🔴 **Нужно исправить:**

Ключ следует определять не внутри компонента, а в рамках функции `map`:

```
.map((el) => <Component key={..} />)
```

2023-08-02 16:38 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +              ingredient.type === 'bun' && ingredientItem(ingredient)
🔴 **Нужно исправить:**

Компоненты следует называть с большой буквы и обращаться к ним в JSX стиле: `<IngredientItem />`

Аналогично ниже

2023-08-02 16:38 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const [current, setCurrent] = useState('bun');
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2023-08-02 16:38 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +        <h2 className="text text_type_main-medium mb-6">Булки</h2>
🟡 **Можно улучшить:**

Группы ингредиентов можно также выделить в отдельный компонент, т.к. код ниже во многом дублируется, а внутрь передавать отфильтрованный список с ингредиентами нужного типа

2023-08-02 16:38 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  function mainItem({ name, price, image }, index) {
🔴 **Нужно исправить:**

Такие небольшие компоненты лучше оставлять прямо в коде или выделять в отдельный директорию/файл, вместо внутренней функции (аналогично как в списке ингредиентов)

2023-08-02 16:38 UTC, randomroot commented on src/components/AppHeader/AppHeader.jsx
> +import appHeader from './AppHeader.module.css';
🟡 **Можно улучшить:**

Лучше поддерживать общий подход к именованию переменной со стилями как `styles` или `classes`, чтобы не возникало путаницы при анализе кода

2023-08-02 16:38 UTC, randomroot commented on src/components/AppHeader/AppHeader.jsx
> +        <NavLink to="*" className={linkActivator}>
🟡 **Можно улучшить:**

Сейчас у вас активируются сразу **две** иконки при нажатии на ленту или профиль. В задании пока нет требований по переходу на другие пути, но сейчас вы можете просто указать уникальные имена экранам, например `/feed` и `/profile`

2023-08-02 18:44 UTC, DangerBadger commented
Add BurgerIngredientsItem and BurgerConstructorItem components;
Add constants.js

2023-08-03 07:07 UTC, randomroot approved these changes
🟢 **Предварительный этап принимается!**

**Текущий PR можно слить в `main` и приступать к выполнению основного этапа.** Напомню, что сдача работы происходит через эту же форму, однако изменения следует делать в новой ветке: `sprint-1/step-2`.

**Хорошего вам настроения и так держать!** 🐈

2023-08-03 07:09 UTC, merged