Sprint 3/step 1
DangerBadger/react-burger pull request #5
Opened 2023-09-10 17:47 UTC by DangerBadger

- Add Register, Login, ForgotPassword, ResetPassWord, Profile, Ingredient/:id, NotFound pages;
- Add internal logic for all pages above;
- Add protection for routes;
- Add redirection function for authorized and non-authorized users;
- Other minor code refactoring.

2023-09-10 18:30 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Правильно использовали Redux Toolkit
- Настроили все редиректы
- Хорошая работа с формами

Необходимо исправить:
- Обновление токена должно работать так же и на изменении данных юзера, так как там тоже используется токен. Так же после обновления токена необходимо повторить ранее неудавшийся запрос.

Для этого используйте обертку над fetch, примерно такую

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-10 18:30 UTC, andryxxa93 commented on src/components/App/App.jsx
> +          <Route path="/register" element={<Register />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-09-10 18:30 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    (store) => store.ingredientsData.ingredients
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-09-10 18:30 UTC, andryxxa93 commented on src/pages/forgot-password/forgot-password.jsx
> +  useEffect(() => {
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-09-11 09:27 UTC, DangerBadger commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    (store) => store.ingredientsData.ingredients
Моих знаний пока не хватает оценить преимущества этого подхода: половина методов использующих useSelector при применении именновнных функций просто перестаёт работать должным образом. Зато из этого всего я понял что лучше избегать деструктуризации, а использовать прямое присваивание свойств из стора, что так же должно уменьшить кол-во рендеров.

2023-09-11 10:12 UTC, DangerBadger commented
Hotfix: 
- Added a refreshToken process to changeUserData function.
Refactor: 
- Added constants for routes;
- Changed routes protection logic.

2023-09-12 00:59 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-12 00:59 UTC, andryxxa93 commented on src/utils/Api.js
> +    return this._requestWithRefresh('/ingredients', {
**Можно лучше**
- Обновление токена должно работать только на тех запросах, которые используют токен, т.е. пока что только запрос данных юзера и обновление

2023-09-12 07:13 UTC, merged